general.import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.normal]
family = "JetbrainsMono Nerd Font"

[window]
padding = {x = 12, y = 8}